### ISSUE TITLE
Interpolations in terraform backend configuration

### ISSUE THREAD

**Issue by posquit0** [1ambda/terraform-all-in-one#1]
As I know, Terrafrom doesn't support interpolations in the backend configuration block. However, I found that you're using some interpolations in there.

Is it possible? I wanna know how you're configuring the backend configuration.

**Comment by 1ambda** [comment]
Hi, currently I am having day off so cant access on my labtop. So this answer might be wrong.

As far as I know its not possible that why its commented out under root-infra.

FYI https://github.com/hashicorp/terraform/issues/17288

**Comment by posquit0** [comment]
Thanks! I just surprised when I see the comments because I also want to do like that.
Sorry for bothering your vacation. Have a good time!
