### ISSUE TITLE
Can I check shell script files for kops operation?

### ISSUE THREAD

**Issue by asbubam** [1ambda/terraform-all-in-one#3]
Thank you for your work. :)

I was trying to understand kops operation automation with **/root-kubernetes/README.md** file.
But I couldn't find shell script files like **generated.kops-env.sh**, **generated.correct-kubectl-context.sh** from /root-kubernetes path.

Can I check shell script files for kops operation?
It'll be really helpful to me.

**Comment by 1ambda** [comment]
Hi, I am Kun. @asbubam 

`generated.*` files are created when applying terraform. In this case, `/root-kubernetes/generated.*` files are generated when applying `root-infra`. 

Here are terraform templates (null-resource) for those.

- `template_kubernetes_kops_env `: https://github.com/1ambda/terraform-all-in-one/blob/master/root-infra/module-kops/kops.tf#L100
- `generated.correct-kubectl-context.sh`: https://github.com/1ambda/terraform-all-in-one/blob/master/root-infra/module-kops/template.correct-kubectl-context.sh

Hope this helps.

Thanks.

**Comment by asbubam** [comment]
@1ambda I've understood. Thank you. Kun. :D
